# Generated by Django 5.0 on 2024-01-05 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("language", models.CharField(max_length=100, verbose_name="Язык")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Категория")),
                ("slug", models.SlugField(max_length=80)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="EventBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/banner")),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Дата мероприятия",
                "verbose_name_plural": "Даты мероприятии",
            },
        ),
        migrations.CreateModel(
            name="EventWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.CharField(max_length=150, verbose_name="Недели")),
                ("slug", models.SlugField(max_length=80)),
            ],
            options={
                "verbose_name": "Неделя",
                "verbose_name_plural": "Недели",
            },
        ),
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Интересы")),
                ("slug", models.SlugField(max_length=80)),
            ],
            options={
                "verbose_name": "Интерес",
                "verbose_name_plural": "Интересы",
            },
        ),
        migrations.CreateModel(
            name="PermanentEvent",
            fields=[
                (
                    "baseevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.baseevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Постоянное мероприятие",
                "verbose_name_plural": "Постоянные мероприятия",
            },
            bases=("events.baseevent",),
        ),
        migrations.CreateModel(
            name="TemporaryEvent",
            fields=[
                (
                    "baseevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.baseevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Временное мероприятие",
                "verbose_name_plural": "Временое мероприятия",
            },
            bases=("events.baseevent",),
        ),
    ]
