# Generated by Django 5.0 on 2024-02-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseevent_org', to='profiles.organizer', verbose_name='Организатор мероприятия'),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='events.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='events.baseevent', verbose_name='Баннеры'),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='events.interests', verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='language',
            field=models.ManyToManyField(related_name='event_language', to='events.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='eventweek',
            name='perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='events.permanentevent', verbose_name='Выберите постоянное событие'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.temporaryevent', verbose_name='Выберите временное событие'),
        ),
        migrations.AlterUniqueTogether(
            name='eventweek',
            unique_together={('perm', 'week')},
        ),
    ]
