# Generated by Django 5.0 on 2024-01-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseevent",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.organizer",
            ),
        ),
        migrations.AddField(
            model_name="baseevent",
            name="category",
            field=models.ManyToManyField(
                related_name="category", to="events.category", verbose_name="Категория"
            ),
        ),
        migrations.AddField(
            model_name="eventbanner",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to="events.baseevent",
                verbose_name="Баннеры",
            ),
        ),
        migrations.AddField(
            model_name="baseevent",
            name="interests",
            field=models.ManyToManyField(
                related_name="interests", to="events.interests", verbose_name="Интересы"
            ),
        ),
        migrations.AddField(
            model_name="permanentevent",
            name="weeks",
            field=models.ManyToManyField(
                related_name="permanentevent",
                to="events.eventweek",
                verbose_name="Постоянное мероприятие",
            ),
        ),
        migrations.AddField(
            model_name="temporaryevent",
            name="dates",
            field=models.ManyToManyField(
                related_name="temporaryevent",
                to="events.eventdate",
                verbose_name="Временное мероприятие",
            ),
        ),
    ]
