# Generated by Django 5.0 on 2023-12-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_category_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('language', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ManyToManyField(to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='EventWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
                ('weeks', models.ManyToManyField(to='events.eventweek')),
            ],
            bases=('events.baseevent',),
        ),
        migrations.CreateModel(
            name='TemporaryEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
            ],
            bases=('events.baseevent',),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RenameModel(
            old_name='EventDay',
            new_name='EventDate',
        ),
        migrations.AddField(
            model_name='temporaryevent',
            name='dates',
            field=models.ManyToManyField(to='events.eventdate'),
        ),
    ]
