# Generated by Django 5.0 on 2023-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_baseevent_eventweek_permanentevent_temporaryevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='baseevent',
            name='interests',
            field=models.ManyToManyField(to='events.interests'),
        ),
    ]
