# Generated by Django 5.0 on 2023-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_category_event_category'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer',
            field=models.ManyToManyField(to='profiles.organiser'),
        ),
    ]
