# Generated by Django 5.0 on 2024-01-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('slug', models.SlugField(help_text='Заполняется автоматически', max_length=80, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('note', models.TextField(verbose_name='Примечания')),
                ('sender', models.CharField(max_length=30, verbose_name='Отправитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.category', verbose_name='Категория')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.recipient', verbose_name='Получатель')),
            ],
        ),
    ]
