version: '3'

services:
  api:
    build: .
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: eventic
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    environment:
      - VIRTUAL_HOST=eventic.pp.ua
      - LETSENCRYPT_HOST=eventic.pp.ua
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eventic_db
      POSTGRES_USER: silver
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres


  nginx:
    image: jwilder/nginx-proxy:1.2
    container_name: docker_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/vhost.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
    depends_on:
      - api

  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/acme.sh

#

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#
#  celery:
#    build: .
#    command: celery -A hotelApi worker -l INFO
#
#    volumes:
#      - .:/usr/src/app/
#    depends_on:
#      - web
#      - redis


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  acme:
  vhost:
  html: