# Generated by Django 4.2.7 on 2024-03-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_seen', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='FollowOrg',
            fields=[
                ('followbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.followbase')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.followbase',),
        ),
        migrations.CreateModel(
            name='FollowPerm',
            fields=[
                ('followbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.followbase')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.followbase',),
        ),
        migrations.CreateModel(
            name='FollowTemp',
            fields=[
                ('followbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.followbase')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.followbase',),
        ),
        migrations.CreateModel(
            name='OrganizationNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='PermanentNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='TemporaryNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.basenotification')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('notifications.basenotification',),
        ),
    ]
