# Generated by Django 4.2.7 on 2024-03-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('notifications', '0001_initial'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followbase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.user'),
        ),
        migrations.AddField(
            model_name='temporarynotification',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.followtemp'),
        ),
        migrations.AddField(
            model_name='permanentnotification',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.followperm'),
        ),
        migrations.AddField(
            model_name='organizationnotification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.baseevent'),
        ),
        migrations.AddField(
            model_name='organizationnotification',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.followorg'),
        ),
        migrations.AddField(
            model_name='followtemp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_events', to='events.eventdate'),
        ),
        migrations.AddField(
            model_name='followperm',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_events', to='events.permanenteventdays'),
        ),
        migrations.AddField(
            model_name='followorg',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_events', to='profiles.organizer'),
        ),
    ]
